<a href="https://colab.research.google.com/github/shivani06kumari/data-structure/blob/main/Numpyassignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import sys

1.  Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)

int64


2.Given a NumPy array 'arr', check if its data type is float64.

arr = np.array([1.5, 2.6, 3.7])

In [ ]:
arr = np.array([1.5, 2.6, 3.7])
is_float64 = arr.dtype == np.float64

print(is_float64)


True


3.Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers

In [ ]:
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)
print(arr.dtype)


[1.+2.j 3.+4.j 5.+6.j]
complex128


4.Convert an existing NumPy array 'arr' of integers to float32 data type.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr_float32 = arr.astype(np.float32)

print(arr_float32)
print(arr_float32.dtype)


[1. 2. 3. 4. 5.]
float32


5.Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [ ]:
arr = np.array([1.123456789, 2.987654321, 3.456789012], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print(arr_float32)
print(arr_float32.dtype)


[1.1234568 2.9876542 3.456789 ]
float32


 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [ ]:
def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype
arr = np.array([[1, 2, 3], [4, 5, 6]])
attributes = array_attributes(arr)

print(attributes)  # Output will be (shape, size, dtype)


((2, 3), 6, dtype('int64'))


7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [ ]:

def array_dimension(arr):
    # Return the dimensionality of the array
    return arr.ndim

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
dimension = array_dimension(arr)

print(dimension)  # Output will be the number of dimensions (e.g., 2 for a 2D array)


2


8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.

In [ ]:
def item_size_info(arr):
    # Get the item size and total size in bytes
    item_size = arr.itemsize
    total_size = arr.nbytes

    # Return the item size and total size as a tuple
    return item_size, total_size

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
size_info = item_size_info(arr)

print(size_info)  # Output will be (item_size, total_size)


(8, 48)


9.Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [ ]:
def array_strides(arr):
    # Return the strides of the array
    return arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)

print(strides)  # Output will be the strides of the array


(24, 8)


10.Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array.

In [ ]:
def shape_stride_relationship(arr):
    # Get the shape and strides of the array
    shape = arr.shape
    strides = arr.strides

    # Return the shape and strides as a tuple
    return shape, strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape_and_strides = shape_stride_relationship(arr)

print(shape_and_strides)  # Output will be (shape, strides)


((2, 3), (24, 8))


11.Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements.

In [ ]:
def create_zeros_array(n):
    # Create a NumPy array of zeros with n elements
    return np.zeros(n)

# Example usage
n = 5
zeros_array = create_zeros_array(n)

print(zeros_array)  # Output will be an array of zeros with n elements


[0. 0. 0. 0. 0.]


12.Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`.

In [ ]:
def create_ones_matrix(rows, cols):
    # Create a 2D NumPy array filled with ones
    return np.ones((rows, cols))

# Example usage
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)

print(ones_matrix)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.

In [ ]:
def generate_range_array(start, stop, step):
    # Create a NumPy array with a range from start to stop with the given step
    return np.arange(start, stop, step)

# Example usage
start = 0
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)

print(range_array)


[0 2 4 6 8]


14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).

In [ ]:
def generate_linear_space(start, stop, num):
    # Create a NumPy array with num equally spaced values between start and stop
    return np.linspace(start, stop, num)

# Example usage
start = 1.0
stop = 5.0
num = 10
linear_space_array = generate_linear_space(start, stop, num)

print(linear_space_array)


[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


15.Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.

In [ ]:
def create_identity_matrix(n):
    # Create an n x n identity matrix
    return np.eye(n)

# Example usage
n = 4
identity_matrix = create_identity_matrix(n)

print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


16.Write a function that takes a Python list and converts it into a NumPy array.

In [ ]:
def list_to_array(py_list):
    # Convert the Python list to a NumPy array
    return np.array(py_list)

# Example usage
py_list = [1, 2, 3, 4, 5]
numpy_array = list_to_array(py_list)

print(numpy_array)


[1 2 3 4 5]


17.Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.


In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)

# Use numpy.view to create a new array object with the same data but a different dtype
view_array = original_array.view(dtype=np.float32)

print("Original array:")
print(original_array)
print("Data type of original array:", original_array.dtype)

print("\nView array:")
print(view_array)
print("Data type of view array:", view_array.dtype)


Original array:
[[1 2 3]
 [4 5 6]]
Data type of original array: int32

View array:
[[1.e-45 3.e-45 4.e-45]
 [6.e-45 7.e-45 8.e-45]]
Data type of view array: float32


18.Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [ ]:


def concatenate_arrays(arr1, arr2, axis=0):
    """
    Concatenate two NumPy arrays along a specified axis.

    Parameters:
    arr1 (np.ndarray): The first array.
    arr2 (np.ndarray): The second array.
    axis (int): The axis along which to concatenate the arrays. Default is 0.

    Returns:
    np.ndarray: The concatenated array.
    """
    # Concatenate the arrays along the specified axis
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenate along axis 0 (vertically)
result_axis0 = concatenate_arrays(arr1, arr2, axis=0)
print("Concatenated along axis 0:")
print(result_axis0)

# Concatenate along axis 1 (horizontally)
result_axis1 = concatenate_arrays(arr1, arr2, axis=1)
print("\nConcatenated along axis 1:")
print(result_axis1)


Concatenated along axis 0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Concatenated along axis 1:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


19.Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
 concatenate`.

In [ ]:

# Create two NumPy arrays with different shapes
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
arr2 = np.array([[7, 8], [9, 10]])       # Shape (2, 2)

# Concatenate the arrays horizontally (along axis 1)
result = np.concatenate((arr1, arr2), axis=1)

print("Array 1:")
print(arr1)
print("Shape of Array 1:", arr1.shape)

print("\nArray 2:")
print(arr2)
print("Shape of Array 2:", arr2.shape)

print("\nConcatenated Result:")
print(result)
print("Shape of Result:", result.shape)


Array 1:
[[1 2 3]
 [4 5 6]]
Shape of Array 1: (2, 3)

Array 2:
[[ 7  8]
 [ 9 10]]
Shape of Array 2: (2, 2)

Concatenated Result:
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]
Shape of Result: (2, 5)


20.Write a function that vertically stacks multiple NumPy arrays given as a list.

In [ ]:

def vertical_stack(arrays):
    """
    Vertically stack multiple NumPy arrays.

    Parameters:
    arrays (list of np.ndarray): List of NumPy arrays to stack.

    Returns:
    np.ndarray: The vertically stacked array.
    """
    # Use numpy.vstack to stack arrays vertically
    return np.vstack(arrays)

# Example usage
array_list = [
    np.array([[1, 2, 3], [4, 5, 6]]),
    np.array([[7, 8, 9], [10, 11, 12]]),
    np.array([[13, 14, 15]])
]

stacked_array = vertical_stack(array_list)

print("Vertically Stacked Array:")
print(stacked_array)


Vertically Stacked Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


21.Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size.

In [ ]:

def create_range_array(start, stop, step):
    """
    Create a NumPy array of integers within a specified range with a given step size.

    Parameters:
    start (int): The starting value of the range.
    stop (int): The ending value of the range (inclusive).
    step (int): The step size between values.

    Returns:
    np.ndarray: The NumPy array with the specified range and step size.
    """
    # Use numpy.arange to create the array
    return np.arange(start, stop + 1, step)

# Example usage
start = 1
stop = 10
step = 2

range_array = create_range_array(start, stop, step)

print("Range Array:")
print(range_array)


Range Array:
[1 3 5 7 9]


22.Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).

In [ ]:


def generate_equally_spaced_array(start, stop, num):
    """
    Generate a NumPy array of equally spaced values between start and stop (inclusive).

    Parameters:
    start (float): The starting value of the range.
    stop (float): The ending value of the range (inclusive).
    num (int): The number of equally spaced values to generate.

    Returns:
    np.ndarray: The NumPy array with the specified number of equally spaced values.
    """
    # Use numpy.linspace to generate the array
    return np.linspace(start, stop, num)

# Example usage
start = 0
stop = 1
num = 10

equally_spaced_array = generate_equally_spaced_array(start, stop, num)

print("Equally Spaced Array:")
print(equally_spaced_array)


Equally Spaced Array:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


23.Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive).

In [ ]:


def generate_logarithmically_spaced_array(start, stop, num):
    """
    Generate a NumPy array of logarithmically spaced values between start and stop (inclusive).

    Parameters:
    start (float): The starting value (base 10 exponent) of the range.
    stop (float): The ending value (base 10 exponent) of the range (inclusive).
    num (int): The number of logarithmically spaced values to generate.

    Returns:
    np.ndarray: The NumPy array with the specified number of logarithmically spaced values.
    """
    # Use numpy.logspace to generate the array
    return np.logspace(np.log10(start), np.log10(stop), num)

# Example usage
start = 1
stop = 1000
num = 5

logarithmically_spaced_array = generate_logarithmically_spaced_array(start, stop, num)

print("Logarithmically Spaced Array:")
print(logarithmically_spaced_array)


Logarithmically Spaced Array:
[   1.            5.62341325   31.6227766   177.827941   1000.        ]


24.Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.

In [ ]:


# Generate a NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame from the NumPy array
df = pd.DataFrame(array, columns=['Column1', 'Column2', 'Column3'])

print("Pandas DataFrame:")
print(df)


Pandas DataFrame:
   Column1  Column2  Column3
0       95       85       81
1       75        9       94
2       10       89       41
3       38       22       67
4       65       72       95


25.Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.

In [ ]:

def replace_negative_with_zero(df, column_name):
    """
    Replace all negative values in a specific column of a Pandas DataFrame with zeros.

    Parameters:
    df (pd.DataFrame): The DataFrame in which to replace negative values.
    column_name (str): The name of the column in which to replace negative values.

    Returns:
    pd.DataFrame: The DataFrame with negative values replaced by zeros in the specified column.
    """
    # Ensure the column exists in the DataFrame
    if column_name in df.columns:
        # Replace negative values with zeros using NumPy
        df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    else:
        print(f"Column '{column_name}' does not exist in the DataFrame.")

    return df

# Example usage
data = {
    'A': [1, -2, 3, -4, 5],
    'B': [10, -20, 30, -40, 50]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Replace negative values in column 'A'
df = replace_negative_with_zero(df, 'A')

print("\nDataFrame after replacing negative values in column 'A':")
print(df)


Original DataFrame:
   A   B
0  1  10
1 -2 -20
2  3  30
3 -4 -40
4  5  50

DataFrame after replacing negative values in column 'A':
   A   B
0  1  10
1  0 -20
2  3  30
3  0 -40
4  5  50


26. Access the 3rd element from the given NumPy array.

 arr = np.array([10, 20, 30, 40, 50])

In [ ]:


# Define the NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Access the 3rd element (index 2)
third_element = arr[2]

print("The 3rd element is:", third_element)


The 3rd element is: 30


. Retrieve the element at index (1, 2) from the 2D NumPy array.

 arr_2d = np.array([[1, 2, 3],

 [4, 5, 6],

 [7, 8, 9]])

In [ ]:


# Define the 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Retrieve the element at index (1, 2)
element = arr_2d[1, 2]

print("The element at index (1, 2) is:", element)


The element at index (1, 2) is: 6


28.Using boolean indexing, extract elements greater than 5 from the given NumPy array.

 arr = np.array([3, 8, 2, 10, 5, 7])

In [ ]:


# Define the NumPy array
arr = np.array([3, 8, 2, 10, 5, 7])

# Use boolean indexing to extract elements greater than 5
greater_than_5 = arr[arr > 5]

print("Elements greater than 5:", greater_than_5)


Elements greater than 5: [ 8 10  7]


29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

 arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:


# Define the NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Slice the array to get elements from index 2 to 5 (inclusive)
sliced_array = arr[2:6]

print("Elements from index 2 to 5 (inclusive):", sliced_array)


Elements from index 2 to 5 (inclusive): [3 4 5 6]


30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

 arr_2d = np.array([[1, 2, 3],

 [4, 5, 6],

 [7, 8, 9]])

In [ ]:


# Define the 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slice the array to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]

print("Extracted sub-array:")
print(sub_array)


Extracted sub-array:
[[2 3]
 [5 6]]


31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.

In [ ]:

def extract_elements(arr, indices):
    """
    Extract elements from a 2D array based on given indices.

    Parameters:
    arr (numpy.ndarray): The input 2D array from which to extract elements.
    indices (numpy.ndarray): A 2D array of indices where each row contains a pair of indices [row, col].

    Returns:
    numpy.ndarray: A 1D array of extracted elements.
    """
    return arr[indices[:, 0], indices[:, 1]]

# Example usage
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

indices = np.array([[0, 1],
                    [2, 2],
                    [1, 0]])

extracted_elements = extract_elements(arr, indices)
print(extracted_elements)


[20 90 40]


32.Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.

In [ ]:
import numpy as np

def extract_elements(arr, indices):
    """
    Extract elements from a 2D array based on the given indices.

    Parameters:
    arr (numpy.ndarray): The input 2D array.
    indices (numpy.ndarray): A 2D array of indices where each pair is [row, col].

    Returns:
    numpy.ndarray: A 1D array of extracted elements.
    """
    return arr[indices[:, 0], indices[:, 1]]

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[0, 1], [1, 2], [2, 0]])
result = extract_elements(arr, indices)
print(result)  # Output: [2 6 7]


[2 6 7]


In [ ]:


def filter_elements(arr, threshold):
    """
    Filter elements greater than a given threshold from a 1D array.

    Parameters:
    arr (numpy.ndarray): The input 1D array.
    threshold (float): The threshold value.

    Returns:
    numpy.ndarray: A 1D array containing elements greater than the threshold.
    """
    return arr[arr > threshold]

# Example usage:
arr = np.array([1, 3, 5, 7, 9])
threshold = 4
result = filter_elements(arr, threshold)
print(result)  # Output: [5 7 9]


[5 7 9]


33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.

In [ ]:
import numpy as np

def extract_elements_3d(arr, x_indices, y_indices, z_indices):
    """
    Extract specific elements from a 3D array using separate arrays of indices for each dimension.

    Parameters:
    arr (numpy.ndarray): The input 3D array.
    x_indices (numpy.ndarray): The array of indices for the first dimension (axis 0).
    y_indices (numpy.ndarray): The array of indices for the second dimension (axis 1).
    z_indices (numpy.ndarray): The array of indices for the third dimension (axis 2).

    Returns:
    numpy.ndarray: A 1D array of extracted elements.
    """
    return arr[x_indices, y_indices, z_indices]

# Example usage:
arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])

x_indices = np.array([0, 1])
y_indices = np.array([1, 0])
z_indices = np.array([2, 1])

result = extract_elements_3d(arr, x_indices, y_indices, z_indices)
print(result)  # Output: [6 8]


[6 8]


34.Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing.

In [ ]:


def filter_elements_two_conditions(arr, condition1, condition2):
    """
    Return elements from an array where both conditions are satisfied.

    Parameters:
    arr (numpy.ndarray): The input array.
    condition1 (numpy.ndarray): A boolean array representing the first condition.
    condition2 (numpy.ndarray): A boolean array representing the second condition.

    Returns:
    numpy.ndarray: A 1D array of elements that satisfy both conditions.
    """
    return arr[condition1 & condition2]

# Example usage:
arr = np.array([1, 3, 5, 7, 9, 11, 13])
condition1 = arr > 4      # Elements greater than 4
condition2 = arr < 10     # Elements less than 10

result = filter_elements_two_conditions(arr, condition1, condition2)
print(result)  # Output: [5 7 9]


[5 7 9]


35.Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.

In [ ]:


def extract_elements_2d(arr, row_indices, col_indices):
    """
    Extract specific elements from a 2D array using separate arrays of row and column indices.

    Parameters:
    arr (numpy.ndarray): The input 2D array.
    row_indices (numpy.ndarray): The array of row indices.
    col_indices (numpy.ndarray): The array of column indices.

    Returns:
    numpy.ndarray: A 1D array of extracted elements.
    """
    return arr[row_indices, col_indices]

# Example usage:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 0, 1])

result = extract_elements_2d(arr, row_indices, col_indices)
print(result)  # Output: [30 40 80]


[30 40 80]


36.Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [ ]:


# Example 2D array of shape (3, 3)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add scalar value 5 to each element using broadcasting
result = arr + 5

print(result)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.

In [ ]:


# Example arrays
arr1 = np.array([[2, 3, 4]])  # Shape (1, 3)
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])  # Shape (3, 4)

# Multiply each row of arr2 by the corresponding element in arr1 using broadcasting
result = arr2 * arr1.T

print(result)


[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


38.Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.

In [ ]:


# Example arrays
arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])  # Shape (4, 3)

# Add arr1 to each row of arr2 using broadcasting
# First, we need to reshape arr1 to be of shape (4, 1) so that it can broadcast properly
result = arr2 + arr1.T

print(result)


[[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


39.Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.

In [ ]:

# Example arrays
arr1 = np.array([[1],
                 [2],
                 [3]])  # Shape (3, 1)
arr2 = np.array([[4, 5, 6]])  # Shape (1, 3)

# Add the arrays using broadcasting
result = arr1 + arr2

print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


40.Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.

In [ ]:


# Example arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  # Shape (2, 3)

arr2 = np.array([[10, 20],
                 [30, 40]])  # Shape (2, 2)

# Reshape arr2 to be compatible with arr1 for broadcasting
arr2_reshaped = arr2[:, :, np.newaxis]  # Shape becomes (2, 2, 1)

# Now perform broadcasting multiplication
result = arr1 * arr2_reshaped

print(result)


[[[ 10  20  30]
  [ 80 100 120]]

 [[ 30  60  90]
  [160 200 240]]]


41.Calculate column wise mean for the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:


# Given array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate column-wise mean
column_wise_mean = np.mean(arr, axis=0)

print(column_wise_mean)


[2.5 3.5 4.5]


42. Find maximum value in each row of the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])


In [ ]:


# Given array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find the maximum value in each row
max_values = np.max(arr, axis=1)

print(max_values)


[3 6]


43. For the given array, find indices of maximum value in each column.

arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:


# Given array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find the indices of the maximum value in each column
max_indices = np.argmax(arr, axis=0)

print(max_indices)


[1 1 1]


44. For the given array, apply cu
stom function to calculate moving sum along rows.

arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:


def moving_sum(arr, window_size):
    """
    Calculate the moving sum along rows for a given window size.

    Parameters:
    arr (numpy.ndarray): The input 2D array.
    window_size (int): The size of the moving window.

    Returns:
    numpy.ndarray: A 2D array with the moving sums.
    """
    # Initialize an empty list to store the moving sums
    result = []

    # Iterate over each row
    for row in arr:
        # Calculate the moving sum for the current row
        row_sums = np.convolve(row, np.ones(window_size), mode='valid')
        result.append(row_sums)

    # Convert the result list to a numpy array
    return np.array(result)

# Given array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Apply the custom function with a window size of 2
window_size = 2
moving_sums = moving_sum(arr, window_size)

print(moving_sums)


[[ 3.  5.]
 [ 9. 11.]]


45. In the given array, check if all elements in each column are even.

arr = np.array([[2, 4, 6], [3, 5, 7]])

In [ ]:

# Given array
arr = np.array([[2, 4, 6],
                [3, 5, 7]])

# Check if all elements in each column are even
# An element is even if it is divisible by 2
is_even = arr % 2 == 0

# Check if all elements in each column are even
all_even = np.all(is_even, axis=0)

print(all_even)


[False False False]


46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix.

original_array = np.array([1, 2, 3, 4, 5, 6])



In [ ]:


# Original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Specify the desired dimensions
m = 2  # Number of rows
n = 3  # Number of columns

# Reshape the array
reshaped_matrix = original_array.reshape(m, n)

print(reshaped_matrix)


[[1 2 3]
 [4 5 6]]


47.Create a function that takes a matrix as input and returns the flattened array.

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])


In [ ]:


def flatten_matrix(matrix):
    """
    Flatten a given matrix into a 1D array.

    Parameters:
    matrix (numpy.ndarray): The input 2D array (matrix).

    Returns:
    numpy.ndarray: The flattened 1D array.
    """
    return matrix.flatten()  # or use matrix.ravel()

# Example usage
input_matrix = np.array([[1, 2, 3],
                         [4, 5, 6]])

flattened_array = flatten_matrix(input_matrix)

print(flattened_array)


[1 2 3 4 5 6]


48. Write a function that concatenates two given arrays along a specified axis.

array1 = np.array([[1, 2], [3, 4]])


array2 = np.array([[5, 6], [7, 8]])


In [ ]:


def concatenate_arrays(arr1, arr2, axis=0):
    """
    Concatenate two arrays along the specified axis.

    Parameters:
    arr1 (numpy.ndarray): The first input array.
    arr2 (numpy.ndarray): The second input array.
    axis (int): The axis along which to concatenate the arrays (default is 0).

    Returns:
    numpy.ndarray: The concatenated array.
    """
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (vertically)
result_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:")
print(result_axis0)

# Concatenate along axis 1 (horizontally)
result_axis1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:")
print(result_axis1)


Concatenated along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


49.Create a function that splits an array into multiple sub-arrays along a specified axis.

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [ ]:


def split_array(arr, num_splits, axis=0):
    """
    Split an array into multiple sub-arrays along the specified axis.

    Parameters:
    arr (numpy.ndarray): The input array.
    num_splits (int): The number of splits.
    axis (int): The axis along which to split the array (default is 0).

    Returns:
    list: A list of numpy.ndarrays, each representing a sub-array.
    """
    return np.array_split(arr, num_splits, axis=axis)

# Example usage
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Split along axis 0 into 3 sub-arrays
sub_arrays_axis0 = split_array(original_array, num_splits=3, axis=0)
print("Split along axis 0:")
for sub_array in sub_arrays_axis0:
    print(sub_array)

# Split along axis 1 into 3 sub-arrays
sub_arrays_axis1 = split_array(original_array, num_splits=3, axis=1)
print("Split along axis 1:")
for sub_array in sub_arrays_axis1:
    print(sub_array)


Split along axis 0:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]
Split along axis 1:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


50. Write a function that inserts and then deletes elements from a given array at specified indices.

original_array = np.array([1, 2, 3, 4, 5])

indices_to_insert = [2, 4]

values_to_insert = [10, 11]

indices_to_delete = [1, 3]


In [ ]:


def insert_and_delete(arr, indices_to_insert, values_to_insert, indices_to_delete):
    """
    Insert elements into an array at specified indices, and then delete elements from the array at specified indices.

    Parameters:
    arr (numpy.ndarray): The input array.
    indices_to_insert (list or numpy.ndarray): Indices at which to insert the values.
    values_to_insert (list or numpy.ndarray): Values to insert at the specified indices.
    indices_to_delete (list or numpy.ndarray): Indices at which to delete the values.

    Returns:
    numpy.ndarray: The resulting array after insertion and deletion.
    """
    # Insert elements
    arr_with_inserts = np.insert(arr, indices_to_insert, values_to_insert)

    # Delete elements
    arr_with_deletions = np.delete(arr_with_inserts, indices_to_delete)

    return arr_with_deletions

# Example usage
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print(result_array)


[ 1 10  4 11  5]


51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.

In [ ]:

# Create arr1 with random integers (e.g., 2x5 array for this example)
arr1 = np.random.randint(1, 100, size=(2, 5))

# Create arr2 with integers from 1 to 10, reshaped to the same shape as arr1
arr2 = np.arange(1, 11).reshape((2, 5))

# Perform element-wise addition
result = arr1 + arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise addition:")
print(result)


arr1:
[[42 72 65 68 69]
 [50 98 93 87  2]]

arr2:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Result of element-wise addition:
[[ 43  74  68  72  74]
 [ 56 105 101  96  12]]


52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [ ]:


# Create arr1 with sequential integers from 10 to 1 (inclusive)
arr1 = np.arange(10, 0, -1)

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise subtraction
result = arr1 - arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise subtraction:")
print(result)


arr1:
[10  9  8  7  6  5  4  3  2  1]

arr2:
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise subtraction:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


53.Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.

In [ ]:


# Create arr1 with random integers (e.g., 3x5 array for this example)
arr1 = np.random.randint(1, 10, size=(3, 5))

# Create arr2 with integers from 1 to 5, reshaped to match arr1
arr2 = np.arange(1, 6).reshape((1, 5))

# Perform element-wise multiplication
result = arr1 * arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise multiplication:")
print(result)


arr1:
[[7 8 2 4 2]
 [7 2 1 3 4]
 [4 4 1 3 7]]

arr2:
[[1 2 3 4 5]]

Result of element-wise multiplication:
[[ 7 16  6 16 10]
 [ 7  4  3 12 20]
 [ 4  8  3 12 35]]


54.Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.

In [ ]:


# Create arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise division
# Reshape arr2 to be broadcastable to the shape of arr1
arr2_reshaped = arr2.reshape((1, -1))  # Reshape arr2 to 1x5 array for broadcasting

# Perform division
result = arr1 / arr2_reshaped

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise division:")
print(result)



arr1:
[ 2  4  6  8 10]

arr2:
[1 2 3 4 5]

Result of element-wise division:
[[2. 2. 2. 2. 2.]]


55.Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [ ]:


# Create arr1 with integers from 1 to 5
arr1 = np.arange(1, 6)

# Create arr2 with the same numbers reversed
arr2 = arr1[::-1]

# Perform element-wise exponentiation
result = arr1 ** arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise exponentiation:")
print(result)


arr1:
[1 2 3 4 5]

arr2:
[5 4 3 2 1]

Result of element-wise exponentiation:
[ 1 16 27 16  5]


56.Write a function that counts the occurrences of a specific substring within a NumPy array of strings.


arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])




In [ ]:

def count_substring_occurrences(arr, substring):
    """
    Count the occurrences of a specific substring within a NumPy array of strings.

    Parameters:
    arr (numpy.ndarray): The input array of strings.
    substring (str): The substring to count occurrences of.

    Returns:
    int: The total count of the substring within the array.
    """
    # Convert the array to a list of strings and count occurrences of the substring
    count = sum(s.count(substring) for s in arr)
    return count

# Example usage
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

# Count occurrences of the substring
occurrences = count_substring_occurrences(arr, substring)

print(f"Occurrences of '{substring}':", occurrences)


Occurrences of 'hello': 3


57.Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [ ]:


def extract_uppercase(arr):
    """
    Extract uppercase characters from a NumPy array of strings.

    Parameters:
    arr (numpy.ndarray): The input array of strings.

    Returns:
    list: A list of strings where each string contains only the uppercase characters from the corresponding input string.
    """
    uppercase_chars = [ ''.join([char for char in s if char.isupper()]) for s in arr ]
    return uppercase_chars

# Example usage
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Extract uppercase characters
uppercase_extracted = extract_uppercase(arr)

print("Extracted uppercase characters:")
print(uppercase_extracted)


Extracted uppercase characters:
['H', 'W', 'OAI', 'GPT']


58.Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])


In [ ]:


def replace_substring(arr, old_substring, new_substring):
    """
    Replace occurrences of a substring in a NumPy array of strings with a new string.

    Parameters:
    arr (numpy.ndarray): The input array of strings.
    old_substring (str): The substring to replace.
    new_substring (str): The new string to replace the old substring with.

    Returns:
    numpy.ndarray: A new NumPy array with the substrings replaced.
    """
    # Apply the replacement operation to each string in the array
    replaced_array = np.array([s.replace(old_substring, new_substring) for s in arr])
    return replaced_array

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'

# Replace occurrences of the substring
result_array = replace_substring(arr, old_substring, new_substring)

print("Original array:")
print(arr)
print("\nModified array:")
print(result_array)


Original array:
['apple' 'banana' 'grape' 'pineapple']

Modified array:
['orange' 'banana' 'grape' 'pineorange']


59.Write a function that concatenates strings in a NumPy array element-wise.

arr1 = np.array(['Hello', 'World'])

arr2 = np.array(['Open', 'AI'])

In [ ]:


def concatenate_strings(arr1, arr2):
    """
    Concatenate strings in two NumPy arrays element-wise.

    Parameters:
    arr1 (numpy.ndarray): The first array of strings.
    arr2 (numpy.ndarray): The second array of strings.

    Returns:
    numpy.ndarray: A new NumPy array with concatenated strings.
    """
    # Ensure both arrays have the same shape
    if arr1.shape != arr2.shape:
        raise ValueError("Arrays must have the same shape for element-wise concatenation.")

    # Concatenate strings element-wise
    concatenated_array = np.char.add(arr1, arr2)
    return concatenated_array

# Example usage
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Concatenate strings element-wise
result_array = concatenate_strings(arr1, arr2)

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nConcatenated Array:")
print(result_array)


Array 1:
['Hello' 'World']

Array 2:
['Open' 'AI']

Concatenated Array:
['HelloOpen' 'WorldAI']


60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:


def longest_string_length(arr):
    """
    Find the length of the longest string in a NumPy array.

    Parameters:
    arr (numpy.ndarray): The input array of strings.

    Returns:
    int: The length of the longest string.
    """
    # Compute the length of each string
    lengths = np.vectorize(len)(arr)

    # Find the maximum length
    max_length = np.max(lengths)

    return max_length

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Find the length of the longest string
max_len = longest_string_length(arr)

print("Array:")
print(arr)
print("\nLength of the longest string:", max_len)


Array:
['apple' 'banana' 'grape' 'pineapple']

Length of the longest string: 9


61.. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.

In [ ]:


# Generate a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Compute the mean
mean = np.mean(dataset)

# Compute the median
median = np.median(dataset)

# Compute the variance
variance = np.var(dataset)

# Compute the standard deviation
std_dev = np.std(dataset)

print("Dataset:")
print(dataset)
print("\nMean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)


Dataset:
[666 715 987 795 864 723 256 879 824 924 849 611 529 669   9 611 176 554
 721 291 979 137 947 223 625 719 863 330 512 262 414 739 774 527 708 434
  16 376 233 878 920  28 617 959 541 242 115 464 163 989 398 327 883 492
 163 644 338 180   3 268 869 698 778  41 825 393 307 694 501 673 733  48
 129  41 538 547 877 640 175 783  22 205 899  44 988 222 287 949 745 441
 713 188 969 827 260 636 821 165 615  82]

Mean: 524.51
Median: 550.5
Variance: 90415.04989999998
Standard Deviation: 300.6909541373002


62.Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.

In [ ]:


# Generate an array of 50 random numbers between 1 and 100
data = np.random.randint(1, 101, size=50)

# Calculate the 25th and 75th percentiles
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print("Data Array:")
print(data)
print("\n25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


Data Array:
[ 42  85  82  86  30  88  72  70   7  60  53  39  66  14  22  61  92  30
  62  78  44  68  96  27  25 100  15  11  61  64  23   3  57  41  92  92
  48  57  13  87  38  29  37  96  60  77  90  81  88  58]

25th Percentile: 31.75
75th Percentile: 81.75


63.Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.

In [ ]:


# Create two arrays representing two sets of variables
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# Compute the correlation coefficient matrix
corr_matrix = np.corrcoef(array1, array2)

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nCorrelation Coefficient Matrix:")
print(corr_matrix)


Array 1:
[1 2 3 4 5]

Array 2:
[5 4 3 2 1]

Correlation Coefficient Matrix:
[[ 1. -1.]
 [-1.  1.]]


64.Create two matrices and perform matrix multiplication using NumPy's `dot` function

In [ ]:


# Create two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication using np.dot
result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nMatrix Multiplication Result:")
print(result)


Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[5 6]
 [7 8]]

Matrix Multiplication Result:
[[19 22]
 [43 50]]


65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.

In [ ]:


# Generate an array of 50 integers between 10 and 1000
data = np.random.randint(10, 1001, size=50)

# Calculate percentiles
percentile_10 = np.percentile(data, 10)
percentile_50 = np.percentile(data, 50)  # This is the median
percentile_90 = np.percentile(data, 90)

# Calculate quartiles
first_quartile = np.percentile(data, 25)
third_quartile = np.percentile(data, 75)

print("Data Array:")
print(data)
print("\n10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (25th Percentile):", first_quartile)
print("Third Quartile (75th Percentile):", third_quartile)


Data Array:
[297 400 447 640 176 402 916 695  95 582 983 396 593 483  62 756 333 147
 995 215 330 600 195  69 544 214 946 848 180 144 729  62 892 924  86 336
 419 557 911 275 723 847 503 814 921 400 924 977 908 852]

10th Percentile: 139.10000000000002
50th Percentile (Median): 523.5
90th Percentile: 924.0
First Quartile (25th Percentile): 280.5
Third Quartile (75th Percentile): 847.75


66.Create a NumPy array of integers and find the index of a specific element.

In [ ]:


# Create a NumPy array of integers
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Define the specific element to find
element = 50

# Find the index of the specific element
index = np.where(array == element)[0]

print("Array:")
print(array)
print("\nIndex of element", element, ":", index)


Array:
[ 10  20  30  40  50  60  70  80  90 100]

Index of element 50 : [4]


In [ ]:


# Create a NumPy array of integers
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Define the specific element to find
element = 50

# Find the index of the specific element
index = np.argmax(array == element)

print("Array:")
print(array)
print("\nIndex of element", element, ":", index)


Array:
[ 10  20  30  40  50  60  70  80  90 100]

Index of element 50 : 4


67. Generate a random NumPy array and sort it in ascending order.

In [ ]:


# Generate a random NumPy array of integers between 1 and 100
random_array = np.random.randint(1, 101, size=10)

# Sort the array in ascending order
sorted_array = np.sort(random_array)

print("Original Array:")
print(random_array)
print("\nSorted Array:")
print(sorted_array)


Original Array:
[ 68  52  47   1  10  33 100  57  97  18]

Sorted Array:
[  1  10  18  33  47  52  57  68  97 100]


68.. Filter elements >20  in the given NumPy array.

arr = np.array([12, 25, 6, 42, 8, 30])


In [ ]:


# Given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_elements = arr[arr > 20]

print("Original Array:")
print(arr)
print("\nFiltered Elements (greater than 20):")
print(filtered_elements)


Original Array:
[12 25  6 42  8 30]

Filtered Elements (greater than 20):
[25 42 30]


69. Filter elements which are divisible by 3 from a given NumPy array.

arr = np.array([1, 5, 8, 12, 15])

In [ ]:


arr = np.array([1, 5, 8, 12, 15])
filtered_arr = arr[arr % 3 == 0]
print(filtered_arr)


[12 15]


70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

arr = np.array([10, 20, 30, 40, 50])


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
filtered_arr = arr[(arr >= 20) & (arr <= 40)]
print(filtered_arr)


[20 30 40]


71.. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

arr = np.array([1, 2, 3])


In [ ]:


arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print(byte_order)


=


72. For the given NumPy array, perform byte swapping in place using `byteswap()`.

arr = np.array([1, 2, 3], dtype=np.int32)


In [ ]:


arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array:", arr)
print("Original byte order:", arr.dtype.byteorder)

arr.byteswap(inplace=True)
print("Array after byte swapping:", arr)
print("Byte order after swapping:", arr.dtype.byteorder)


Original array: [1 2 3]
Original byte order: =
Array after byte swapping: [16777216 33554432 50331648]
Byte order after swapping: =


73.For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:

# Example array
arr = np.array([1, 2, 3, 4], dtype='int32')

print("Original Array (byte order):", arr.dtype.byteorder)

# Swap byte order without modifying the original array
swapped_arr = arr.view(arr.dtype.newbyteorder('<'))  # Use '<' for little-endian or '>' for big-endian

# Print the new array with swapped byte order
print("\nArray with Swapped Byte Order:", swapped_arr)


Original Array (byte order): =

Array with Swapped Byte Order: [1 2 3 4]


74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.


arr = np.array([1, 2, 3], dtype=np.int32)


In [ ]:


# Example array
arr = np.array([1, 2, 3, 4], dtype='int32')

# Desired endianness (e.g., '<' for little-endian or '>' for big-endian)
desired_endianness = '<'  # Set the desired byte order here

# Swap byte order conditionally based on system endianness
if arr.dtype.byteorder != desired_endianness:
    swapped_arr = arr.view(arr.dtype.newbyteorder(desired_endianness))
else:
    swapped_arr = arr.copy()  # No change needed if already in desired endianness

# Print the original and swapped arrays
print("Original Array:", arr)
print("Array with Swapped Byte Order:", swapped_arr)


Original Array: [1 2 3 4]
Array with Swapped Byte Order: [1 2 3 4]


75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`.

arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:


# Create the array
arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array:", arr)
print("Original byte order:", arr.dtype.byteorder)

# Check system endianness
system_endian = '>' if sys.byteorder == 'big' else '<'

# Determine if byte swapping is necessary
if arr.dtype.byteorder == '=' or arr.dtype.byteorder == system_endian:
    print("Byte swapping is not necessary.")
else:
    print("Byte swapping is necessary.")


Original array: [1 2 3]
Original byte order: =
Byte swapping is not necessary.


76.Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.


In [ ]:


# Create the original array
arr1 = np.arange(1, 11)
print("Original array (arr1):", arr1)

# Create a copy of arr1
copy_arr = arr1.copy()
print("Copy of array (copy_arr):", copy_arr)

# Modify an element in the copy
copy_arr[0] = 100
print("Modified copy array (copy_arr):", copy_arr)

# Check if the original array is affected
print("Original array after modification (arr1):", arr1)


Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Copy of array (copy_arr): [ 1  2  3  4  5  6  7  8  9 10]
Modified copy array (copy_arr): [100   2   3   4   5   6   7   8   9  10]
Original array after modification (arr1): [ 1  2  3  4  5  6  7  8  9 10]


77.Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.




In [ ]:


# Create a 2D NumPy array with random integers
matrix = np.random.randint(0, 10, size=(3, 3))
print("Original matrix:\n", matrix)

# Extract a slice from the matrix
view_slice = matrix[1:, 1:]
print("View slice before modification:\n", view_slice)

# Modify an element in the slice
view_slice[0, 0] = 99
print("View slice after modification:\n", view_slice)

# Check if the original matrix is affected
print("Original matrix after modification:\n", matrix)


Original matrix:
 [[3 3 3]
 [1 2 3]
 [0 1 5]]
View slice before modification:
 [[2 3]
 [1 5]]
View slice after modification:
 [[99  3]
 [ 1  5]]
Original matrix after modification:
 [[ 3  3  3]
 [ 1 99  3]
 [ 0  1  5]]


78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [ ]:


# Create the array with sequential integers
array_a = np.arange(1, 13).reshape((4, 3))
print("Original array (array_a):\n", array_a)

# Extract a slice from array_a
view_b = array_a[1:3, 1:3]
print("View slice before modification (view_b):\n", view_b)

# Broadcast addition of 5 to view_b
view_b += 5
print("View slice after modification (view_b):\n", view_b)

# Check if the original array is affected
print("Original array after modification (array_a):\n", array_a)


Original array (array_a):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
View slice before modification (view_b):
 [[5 6]
 [8 9]]
View slice after modification (view_b):
 [[10 11]
 [13 14]]
Original array after modification (array_a):
 [[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]


79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.




In [ ]:


# Create the original array with values from 1 to 8
orig_array = np.arange(1, 9).reshape((2, 4))
print("Original array (orig_array):\n", orig_array)

# Create a reshaped view of shape (4, 2) from orig_array
reshaped_view = orig_array.reshape((4, 2))
print("Reshaped view (reshaped_view) before modification:\n", reshaped_view)

# Modify an element in reshaped_view
reshaped_view[0, 0] = 99
print("Reshaped view (reshaped_view) after modification:\n", reshaped_view)

# Check if the original array is affected
print("Original array (orig_array) after modification:\n", orig_array)


Original array (orig_array):
 [[1 2 3 4]
 [5 6 7 8]]
Reshaped view (reshaped_view) before modification:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Reshaped view (reshaped_view) after modification:
 [[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]
Original array (orig_array) after modification:
 [[99  2  3  4]
 [ 5  6  7  8]]


80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [ ]:


# Create the array with random integers
data = np.random.randint(1, 10, size=(3, 4))
print("Original data array:\n", data)

# Extract elements greater than 5 and create a copy
data_copy = data[data > 5].copy()
print("Data copy (elements > 5) before modification:\n", data_copy)

# Modify an element in data_copy
data_copy[0] = 99
print("Data copy (elements > 5) after modification:\n", data_copy)

# Check if the original array is affected
print("Original data array after modification:\n", data)


Original data array:
 [[4 7 1 6]
 [1 2 8 3]
 [3 8 2 3]]
Data copy (elements > 5) before modification:
 [7 6 8 8]
Data copy (elements > 5) after modification:
 [99  6  8  8]
Original data array after modification:
 [[4 7 1 6]
 [1 2 8 3]
 [3 8 2 3]]


81.Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.

In [ ]:


# Create two matrices of identical shape with integer values
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[6, 5, 4], [3, 2, 1]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Perform addition
addition_result = A + B
print("Addition result (A + B):\n", addition_result)

# Perform subtraction
subtraction_result = A - B
print("Subtraction result (A - B):\n", subtraction_result)


Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[6 5 4]
 [3 2 1]]
Addition result (A + B):
 [[7 7 7]
 [7 7 7]]
Subtraction result (A - B):
 [[-5 -3 -1]
 [ 1  3  5]]


82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication

In [ ]:


# Generate two matrices C (3x2) and D (2x4)
C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))

print("Matrix C (3x2):\n", C)
print("Matrix D (2x4):\n", D)

# Perform matrix multiplication
result = C @ D  # or np.dot(C, D)

print("Result of C @ D:\n", result)


Matrix C (3x2):
 [[6 6]
 [3 2]
 [3 2]]
Matrix D (2x4):
 [[1 3 5 1]
 [1 1 6 4]]
Result of C @ D:
 [[12 24 66 30]
 [ 5 11 27 11]
 [ 5 11 27 11]]


83.Create a matrix `E` and find its transpose.

In [ ]:


# Create a matrix E
E = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix E:\n", E)

# Find the transpose of matrix E
E_transpose = E.T
# Alternatively, you can use np.transpose(E)
# E_transpose = np.transpose(E)

print("Transpose of Matrix E:\n", E_transpose)


Matrix E:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of Matrix E:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


84.Generate a square matrix `F` and compute its determinant

In [ ]:


# Generate a square matrix F (e.g., 3x3) with random integers
F = np.random.randint(1, 10, size=(3, 3))
print("Matrix F:\n", F)

# Compute the determinant of matrix F
determinant_F = np.linalg.det(F)
print("Determinant of Matrix F:", determinant_F)


Matrix F:
 [[3 9 7]
 [8 6 8]
 [5 3 8]]
Determinant of Matrix F: -186.00000000000009


85.Create a square matrix `G` and find its inverse.

In [ ]:


# Create a square matrix G (e.g., 3x3) with random integers
G = np.array([[4, 7, 2], [3, 6, 1], [2, 5, 3]])
print("Matrix G:\n", G)

# Compute the inverse of matrix G
try:
    G_inv = np.linalg.inv(G)
    print("Inverse of Matrix G:\n", G_inv)
except np.linalg.LinAlgError:
    print("Matrix G is singular and does not have an inverse.")


Matrix G:
 [[4 7 2]
 [3 6 1]
 [2 5 3]]
Inverse of Matrix G:
 [[ 1.44444444 -1.22222222 -0.55555556]
 [-0.77777778  0.88888889  0.22222222]
 [ 0.33333333 -0.66666667  0.33333333]]
